spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plm-system
    username: root
    password: 12345

    maxActive: 100
    removeAbandoned: true
    removeAbandonedTimeout: 60
    logAbandoned: true
    abandon-when-percentage-full: 50
    test-on-borrow: true
    validation-query: SELECT 1
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  profiles.active: ${spring.profile.maven}
  file.properties.maven: "config/application-local.yml"